### ISSUE TITLE
Exception on startup with IDEA 2022.2.4

### ISSUE THREAD

**Issue by Leo40Git** [Earthcomputer/class-file-indexer#30]
```
java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@4fc80a7d
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
	at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:268)
	at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:233)
	at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:215)
	at net.earthcomputer.classfileindexer.a.componentsInitialized(SourceFile:81)
	at com.intellij.idea.ApplicationLoader$callAppInitialized$1$1.run(ApplicationLoader.kt:485)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.bytebuddy.agent.Attacher.install(Attacher.java:110)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:603)
	... 11 more
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:166)
	... 17 more

```

**Comment by FxMorin** [comment]
Use the distribution zip, not the libs jar
